export const GET_ALL_ASTEROIDS = "GET_ALL_ASTEROIDS";
export const GET_ALL_ASTEROIDS_FAILED = "GET_ALL_ASTEROIDS_FAILED";
export const GET_ASTEROID_DETAILS = "GET_ASTEROID_DETAILS";
export const GET_ASTEROID_DETAILS_FAILED = "GET_ASTEROID_DETAILS_FAILED";
